name: CD

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: course.prafdin.ru
          username: defoult
          port: 2471
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          timeout: 60s
          command_timeout: 10m
          debug: true
          script: |
            set -euxo pipefail
            sudo -n systemctl status frpc --no-pager
            cd /home/defoult/OIS
            bash -x ./deploy.sh
