name: CD Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: course.prafdin.ru
          username: defoult
          port: 2471
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail
            echo "🔄 Pull latest image from GHCR"
            docker login ghcr.io -u defoult13 -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/defoult13/catty-reminders-app:latest || true

            echo "🧹 Stop and remove old container if exists"
            docker rm -f catty-reminders || true

            echo "🚀 Run new container"
            docker run -d --name catty-reminders -p 8181:8181 ghcr.io/defoult13/catty-reminders-app:latest

            echo "✅ Deployment complete"
